apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webapp
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: prod
  template:
    metadata:
      name: 'webapp-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ganeshkumarappsre/gitops-argocd-lab.git
        targetRevision: main
        path: charts/webapp
        helm:
          valueFiles:
            - '../../envs/{{env}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'webapp-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
